### ISSUE TITLE
自动滚动似乎有点问题

### ISSUE THREAD

**Issue by hqweay** [Tomotoes/react-terminal#1]
![image](https://user-images.githubusercontent.com/23608642/99144395-7a18ca80-26a0-11eb-9197-436e98b85f8e.png)
如图，终端打印后输入框被遮盖了。
我不大懂 react 的语法，看到源码似乎有 print 后 autoScroll 的逻辑，但似乎没有起作用。
试了下，用 componentDidUpdate 使用 autoScroll 有效。

**Comment by SimonAKing** [comment]
奇怪, 有控制台报错信息嘛? 我这边无法复现.

**Comment by hqweay** [comment]
没有啥报错信息。我用手机没问题，可能是我环境的问题吧……囧囧
另空 `cd` 指令没有做非空判断，控制台会报错。
![image](https://user-images.githubusercontent.com/23608642/99147500-73984c00-26bc-11eb-883e-f693dd21325e.png)

**Comment by SimonAKing** [comment]
Thx, 我这就看一下.

**Comment by SimonAKing** [comment]
我刚刚推了一版, 解决了 trim 以及回滚历史命令时 输入位置错误问题.
