### ISSUE TITLE
输入不存在的命令补全显示会隐藏

### ISSUE THREAD

**Issue by zhengqijun0121** [Tomotoes/react-terminal#2]
1. 输入不存在的命令补全显示会隐藏
2. 不能补全内置命令

**Comment by zhengqijun0121** [comment]
手机端的显示有滚动条，可以设置匹配手机的高度显示吗？

**Comment by SimonAKing** [comment]
输入不存在的命令补全显示会隐藏
不能补全内置命令

我这边已复现, 等我修复下~

**Comment by SimonAKing** [comment]
> 手机端的显示有滚动条，可以设置匹配手机的高度显示吗？

这个可以具体下 手机端的高度嘛.. 我这边是没有滚动条的..

**Comment by SimonAKing** [comment]
> 1. 输入不存在的命令补全显示会隐藏
> 2. 不能补全内置命令

我修复了这个问题, 可以在check下

**Comment by zhengqijun0121** [comment]
补全之后ls和help命令现在出现了问题
